### ISSUE TITLE
404s occuring on DNN instances intermittently

### ISSUE THREAD

**Issue by Creech99** [davidjrh/dnn.rediscachingprovider#20]
Hi David,

So we've been fighting an issue with pages intermittently 404ing in our environment once they start to use the REDIS caching provider. 

We are currently running REDIS version 3.00.504 on Windows with the REDIS 2.1 provider.

I currently have REDIS set to debugging loglevel and I'm not seeing anything jump out as a possible cause.
We are currently running DNN 7.4.2 CE which I understand you don't support, but must run in the short term.

Could this lower version of DNN be causing this and/or do have any suggestions?

**Comment by davidjrh** [comment]
DNN 7.4.2 CE and Redis 2.1 provider? Starting with the 2.0 provider, I needed to set DNN Platform 8.0 as minimum requirement because of the new Output caching provider that was not available on previous versions https://github.com/davidjrh/dnn.rediscachingprovider/blob/master/RedisCachingProvider/RedisCachingProvider.dnn#L18

**Comment by Creech99** [comment]
Thanks David for the reply.

We will be upgrading to 8.0 soon and were hoping to use your provider on DNN 7.4.2 in the short term. I'll do some testing to see if the problem occurs in our test environment on DNN 8.x.

**Comment by davidjrh** [comment]
I'm going to close this issue. If the problem occurs again, just reopen it.

**Comment by calebickler** [comment]
Can you provide any information on what is causing the 404s? We are currently experiencing the 404s but we are unable to update from 7.4.2.
